### ISSUE TITLE
Rational approximations

### ISSUE THREAD

**Issue by roger-** [DKenefake/OptimalPoly#1]
Thanks for this, was about to start writing my own remez implementation but yours is very clean!

Have you thought about extending it to rational approximations?

**Comment by DKenefake** [comment]
Hey, thank you! This repo was mostly a learning exercise for a class in approximation taught by Prof. Foucart, @foucart. It was his suggestion for the basis change to Chebyshev polynomials, and that improved the numerics.

I am not sure if I have an open day in the coming months to implement this, but I am sure there is something in Prof. Foucart's repos that would help.
